# Podfile for iOS with Yandex Ads and VK Ads (MyTarget)

platform :ios, '13.0'

# Specify the Xcode project
project 'TestAdMobApp.xcodeproj'

target 'TestAdMobApp' do
  use_frameworks!
  
  # Yandex Mobile Ads SDK (requires iOS 13+)
  pod 'YandexMobileAds', '~> 7.17.1'
  
  # VK Ads (MyTarget) SDK
  pod 'myTargetSDK', '~> 5.35.1'
  
  # AdMob (already included via plugin)
  # pod 'Google-Mobile-Ads-SDK'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
