# Podfile for iOS with VK Ads (MyTarget)
# Yandex Ads will be integrated via direct XCFramework download

platform :ios, '13.0'

# Specify the Xcode project
project 'TestAdMobApp.xcodeproj'

target 'TestAdMobApp' do
  use_frameworks!
  
  # VK Ads (MyTarget) SDK - works fine with CocoaPods
  pod 'myTargetSDK', '~> 5.35.1'
  
  # Yandex Mobile Ads - will be added as XCFramework manually
  # This avoids VGSLFundamentals Swift compilation issues in CI
  
  # AdMob (already included via plugin)
  # pod 'Google-Mobile-Ads-SDK'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      
      # Swift compatibility
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'
    end
  end
end
